### ISSUE TITLE
Explaining the prototype chain a little bit

### ISSUE THREAD

**Issue by cernanb** [learn-co-curriculum/js-object-oriented-prototypes-readme#3]
`What the above code illustrates is each JavaScript object has reference to attributes declared on its constructor's prototype. So both sally and freddy have reference to the sayHello attribute that points to a specific function. Not only that, but they have reference to exactly the same function. So regardless of the number of objects produced from the User constructor, there will be only one declared sayHello function.`

Would there be value in explaining how sally and freddy first look to themselves to see if they have a sayHello property...and if not, they then look to prototype object they point to? 
@jmburges @gj

**Comment by gj** [comment]
@JeffKatzy ^

**Comment by maxwellbenton** [comment]
Thank you for spotting this and providing feedback, @cernanb.

We have updated the materials to discuss this concept and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
