### ISSUE TITLE
var should be replaced 

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/js-object-oriented-prototypes-readme#4]
In this section, in the code snippet, seems like var Sarah should be let Sarah, for consistency. 

BEHOLD THE PROTOTYPE!!
Javascript objects have something called a Prototype. Let's check it out.

function User(name, email) {
  this.name = name;
  this.email = email;
}
 
User.prototype.sayHello = function() {
  console.log(`Hello everybody, my name is ${this.name}`);
}
 
var sarah = new User("sarah", "sarah@aol.com");

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
Thanks for contributing. 💙
