### ISSUE TITLE
Annoying that the sidebar covers the proceed to next lesson button

### ISSUE THREAD

**Issue by tahseen447** [learn-co-curriculum/js-object-oriented-prototypes-readme#6]

**Comment by tahseen447** [comment]
<img width="960" alt="flatironerror" src="https://user-images.githubusercontent.com/27441092/48395723-04eb1700-e6cd-11e8-97b9-8d3785f80223.png">

only option is to refresh the page and press next lesson button as fast as you can before the side bar group study appears and covers the whole thing.

**Comment by tahseen447** [comment]
closed the issue by mistake

**Comment by sgharms** [comment]
Hi there! This request sounds like an improvement to the Learn platform.

Our product team loves to hear about our Learners' innovative interface
improvements. You can reach them at support@learn.co. Alternatively, if Learn
is misbehaving, please direct your bug report to bugs@learn.co.

[Raising issues onGitHub][raise] should be reserved for problems with
the curriculum itself (doesn't work, throws a Ruby error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
